version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
orbs:
  ruby: circleci/ruby@1.0

jobs:
  rubocop:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.1-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  checks:
    jobs:
      - rubocop
